FROM nginx:alpine
COPY index.html print.html style.css script.js auth.js favicon.svg arrange_task.html arrange_subtask.html manage_task.html settings.html /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/conf.d/default.conf
